[package]
name = "writer"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4"
libc = "0.2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
schema = { path = "../schema" }
collector = { path = "../collector" }

[dev-dependencies]
tempfile = "3"
